# Generated by Django 5.0.3 on 2025-02-08 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_estudante_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='codigo',
        ),
    ]
